/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulario_Integradores;

import javax.swing.JOptionPane;

/**
 *
 * @author Charlie Cordova
 */
public class frm04_RegistroNacional extends javax.swing.JFrame {

    /**
     * Creates new form frm05_RegistroNacional
     */
    public frm04_RegistroNacional() {
        initComponents();
        setLocationRelativeTo(this);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Registro");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        jLabel2.setText("Numero de Provincia:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        jLabel3.setText("Numero de Partido:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel4.setText("Numero de Localidad:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel5.setText("C. habitantes hombes:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, -1));

        jLabel6.setText("C. habitantes mujeres:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, -1, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 130, 30));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 130, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccione uno>", "Provincia 1 - 12", "Provincia 12 - 24" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 250, 30));

        jButton1.setText("Literal A");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        jButton2.setText("Literal B");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        jButton3.setText("Literal C");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, -1, -1));

        jButton4.setText("Literal D");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, -1, -1));

        jButton5.setText("Cancelar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, -1, -1));

        jButton6.setText("Ingresar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccione uno>", "Partido 1", "Partido 2", "Partido 3" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 150, 30));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccione uno>", "Localidad 1", "Localidad 2", "Localidad 3" }));
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 150, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String numpro = "", numpart = "", numlocal = "", Mlp = "", Mlp2 = "", Mlp3 = "", Provinciamayorcantidad = "",
            Provinciamenorcantidad = "", Localidadmayorcantmujeres = "", pm = "", pmcm = "";
    int chh = 0, chm = 0, totall1 = 0, totall2 = 0, totall3 = 0,
            totall12 = 0, totall22 = 0, totall32 = 0,
            totall13 = 0, totall23 = 0, totall33 = 0,
            totall1_ = 0, totall2_ = 0, totall3_ = 0,
            totall12_ = 0, totall22_ = 0, totall32_ = 0,
            totall13_ = 0, totall23_ = 0, totall33_ = 0,
            totalp1 = 0, totalp2 = 0, totalp3 = 0, totalprovincia1 = 0, totalprovincia2 = 0,
            mlp1 = 0, mlp2 = 0, mlp3 = 0, provinciamayorcantidad = 0, provinciamenorcantidad = Integer.MAX_VALUE,
            tml1 = 0, tml2 = 0, tml3 = 0,
            tml12 = 0, tml22 = 0, tml32 = 0,
            tml13 = 0, tml23 = 0, tml33 = 0,
            tml1_ = 0, tml2_ = 0, tml3_ = 0,
            tml12_ = 0, tml22_ = 0, tml32_ = 0,
            tml13_ = 0, tml23_ = 0, tml33_ = 0, localidadmayorcantmujeres = 0;

    public void proced_Literal_a() {
        if (numpro.equals("Provincia 1 - 12")) {
            if (numpart.equals("Partido 1")) {
                if (numlocal.equals("Localidad 1")) {
                    totall1 = chh + chm;
                    totalp1 += totall1;
                    totalprovincia1 += totall1;
                    tml1 += chm; 
                } else if (numlocal.equals("Localidad 2")) {
                    totall2 = chh + chm;
                    totalp1 += totall2;
                    totalprovincia1 += totall2;
                    tml2 += chm; 
                } else if (numlocal.equals("Localidad 3")) {
                    totall3 = chh + chm;
                    totalp1 += totall3;
                    totalprovincia1 += totall3;
                    tml3 += chm; 
                }
            } else if (numpart.equals("Partido 2")) {
                if (numlocal.equals("Localidad 1")) {
                    totall12 = chh + chm;
                    totalp2 += totall12;
                    totalprovincia1 += totall12;
                    tml12 += chm; 
                } else if (numlocal.equals("Localidad 2")) {
                    totall22 = chh + chm;
                    totalp2 += totall22;
                    totalprovincia1 += totall22;
                    tml22 += chm; 
                } else if (numlocal.equals("Localidad 3")) {
                    totall32 = chh + chm;
                    totalp2 += totall32;
                    totalprovincia1 += totall32;
                    tml32 += chm;
                }
            } else if (numpart.equals("Partido 3")) {
                if (numlocal.equals("Localidad 1")) {
                    totall13 = chh + chm;
                    totalp3 += totall13;
                    totalprovincia1 += totall13;
                    tml13 += chm;
                } else if (numlocal.equals("Localidad 2")) {
                    totall23 = chh + chm;
                    totalp3 += totall23;
                    totalprovincia1 += totall23;
                    tml23 += chm;
                } else if (numlocal.equals("Localidad 3")) {
                    totall33 = chh + chm;
                    totalp3 += totall33;
                    totalprovincia1 += totall33;
                    tml33 += chm;
                }
            }
        } else if (numpro.equals("Provincia 12 - 24")) {
            if (numpart.equals("Partido 1")) {
                if (numlocal.equals("Localidad 1")) {
                    totall1_ = chh + chm;
                    totalp1 += totall1_;
                    totalprovincia2 += totall1_;
                    tml1_ += chm; 
                } else if (numlocal.equals("Localidad 2")) {
                    totall2_ = chh + chm;
                    totalp1 += totall2_;
                    totalprovincia2 += totall2_;
                    tml2_ += chm; 
                } else if (numlocal.equals("Localidad 3")) {
                    totall3_ = chh + chm;
                    totalp1 += totall3_;
                    totalprovincia2 += totall3_;
                    tml3_ += chm; 
                }
            } else if (numpart.equals("Partido 2")) {
                if (numlocal.equals("Localidad 1")) {
                    totall12_ = chh + chm;
                    totalp2 += totall12_;
                    totalprovincia2 += totall12_;
                    tml12_ = chm;
                } else if (numlocal.equals("Localidad 2")) {
                    totall22_ = chh + chm;
                    totalp2 += totall22_;
                    totalprovincia2 += totall22_;
                    tml22_ = chm;
                } else if (numlocal.equals("Localidad 3")) {
                    totall32_ = chh + chm;
                    totalp2 += totall32_;
                    totalprovincia2 += totall32_;
                    tml32_ = chm;
                }
            } else if (numpart.equals("Partido 3")) {
                if (numlocal.equals("Localidad 1")) {
                    totall13_ = chh + chm;
                    totalp3 += totall13_;
                    totalprovincia2 += totall13_;
                    tml13_ = chm;
                } else if (numlocal.equals("Localidad 2")) {
                    totall23_ = chh + chm;
                    totalp3 += totall23_;
                    totalprovincia2 += totall23_;
                    tml23_ = chm;
                } else if (numlocal.equals("Localidad 3")) {
                    totall33_ = chh + chm;
                    totalp3 += totall33_;
                    totalprovincia2 += totall33_;
                    tml33_ = chm;
                }
            }
        }
    }

    public void proced_literalA2() {
        if (numpart.equals("Partido 1")) {
            if (totall1 > mlp1) {
                mlp1 = totall1;
                Mlp = "Localidad 1";
            } else if (totall2 > mlp1) {
                mlp1 = totall2;
                Mlp = "Localidad 2";
            } else if (totall3 > mlp1) {
                mlp1 = totall3;
                Mlp = "Localidad 3";
            }
        }
        if (totall1_ > mlp1) {
            mlp1 = totall1_;
            Mlp = "Localidad 1";
        } else if (totall2_ > mlp1) {
            mlp1 = totall2_;
            Mlp = "Localidad 2";
        } else if (totall3_ > mlp1) {
            mlp1 = totall3_;
            Mlp = "Localidad 3";
        }
    }

    public void proced_literalA22() {
        if (numpart.equals("Partido 2")) {
            if (totall12 > mlp2) {
                mlp2 = totall12;
                Mlp2 = "Localidad 1";
            } else if (totall22 > mlp2) {
                mlp2 = totall22;
                Mlp2 = "Localidad 2";
            } else if (totall32 > mlp2) {
                mlp2 = totall32;
                Mlp2 = "Localidad 3";
            }
        }
        if (totall12_ > mlp2) {
            mlp2 = totall12_;
            Mlp2 = "Localidad 1";
        } else if (totall22_ > mlp2) {
            mlp2 = totall22_;
            Mlp2 = "Localidad 2";
        } else if (totall32_ > mlp2) {
            mlp2 = totall32_;
            Mlp2 = "Localidad 3";
        }
    }

    public void proced_literalA23() {
        if (numpart.equals("Partido 3")) {
            if (totall13 > mlp3) {
                mlp3 = totall13;
                Mlp3 = "Localidad 1";
            } else if (totall23 > mlp3) {
                mlp3 = totall23;
                Mlp3 = "Localidad 2";
            } else if (totall33 > mlp3) {
                mlp3 = totall33;
                Mlp3 = "Localidad 3";
            }
        }
        if (totall13_ > mlp3) {
            mlp3 = totall13_;
            Mlp3 = "Localidad 1";
        } else if (totall23_ > mlp3) {
            mlp3 = totall23_;
            Mlp3 = "Localidad 2";
        } else if (totall33_ > mlp3) {
            mlp3 = totall33_;
            Mlp3 = "Localidad 3";
        }
    }

    public void Literal_B() {
        if (totalprovincia1 >= provinciamayorcantidad) {
            provinciamayorcantidad = totalprovincia1;
            Provinciamayorcantidad = "Provincia 1 - 12";
        }
        if (totalprovincia2 >= provinciamayorcantidad) {
            provinciamayorcantidad = totalprovincia2;
            Provinciamayorcantidad = "Provincia 12 - 24";
        }
    }

    public void Literal_C() {
        if (provinciamenorcantidad >= totalprovincia1) {
            provinciamenorcantidad = totalprovincia1;
            Provinciamenorcantidad = "Provincia 1 - 12";
        }
        if (provinciamenorcantidad >= totalprovincia2) {
            provinciamenorcantidad = totalprovincia2;
            Provinciamenorcantidad = "Provincia 12 - 24";
        }
    }
    
    public void Literal_D(){
        if(tml1 > localidadmayorcantmujeres){
            localidadmayorcantmujeres = tml1;
            Localidadmayorcantmujeres = "Localidad 1";
            pm = "Partido 1";
            pmcm = "Provincia 1 - 12";
        }else if(tml1_> localidadmayorcantmujeres){
            localidadmayorcantmujeres = tml1_;
            Localidadmayorcantmujeres = "Localidad 1";
            pm = "Partido 1";
            pmcm = "Provincia 12 - 24";
        }
        if(tml2 > localidadmayorcantmujeres){
            localidadmayorcantmujeres = tml2;
            Localidadmayorcantmujeres = "Localidad 2";
            pm = "Partido 1";
            pmcm = "Provincia 1 - 12";
        }else if(tml2_> localidadmayorcantmujeres){
            localidadmayorcantmujeres = tml2_;
            Localidadmayorcantmujeres = "Localidad 2";
            pm = "Partido 1";
            pmcm = "Provincia 12 - 24";
        }
        if(tml3 > localidadmayorcantmujeres){
            localidadmayorcantmujeres = tml3;
            Localidadmayorcantmujeres = "Localidad 3";
            pm = "Partido 1";
            pmcm = "Provincia 1 - 12";
        }else if(tml3_> localidadmayorcantmujeres){
            localidadmayorcantmujeres = tml3_;
            Localidadmayorcantmujeres = "Localidad 3";
            pm = "Partido 1";
            pmcm = "Provincia 12 - 24";
        }
        
        
        if(tml12 > localidadmayorcantmujeres){
            localidadmayorcantmujeres = tml12;
            Localidadmayorcantmujeres = "Localidad 1";
            pm = "Partido 2";
            pmcm = "Provincia 1 - 12";
        }else if(tml12_> localidadmayorcantmujeres){
            localidadmayorcantmujeres = tml12_;
            Localidadmayorcantmujeres = "Localidad 1";
            pm = "Partido 2";
            pmcm = "Provincia 12 - 24";
        }
        if(tml22 > localidadmayorcantmujeres){
            localidadmayorcantmujeres = tml22;
            Localidadmayorcantmujeres = "Localidad 2";
            pm = "Partido 2";
            pmcm = "Provincia 1 - 12";
        }else if(tml22_> localidadmayorcantmujeres){
            localidadmayorcantmujeres = tml22_;
            Localidadmayorcantmujeres = "Localidad 2";
            pm = "Partido 2";
            pmcm = "Provincia 12 - 24";
        }
        if(tml32 > localidadmayorcantmujeres){
            localidadmayorcantmujeres = tml32;
            Localidadmayorcantmujeres = "Localidad 3";
            pm = "Partido 2";
            pmcm = "Provincia 1 - 12";
        }else if(tml32_> localidadmayorcantmujeres){
            localidadmayorcantmujeres = tml32_;
            Localidadmayorcantmujeres = "Localidad 3";
            pm = "Partido 2";
            pmcm = "Provincia 12 - 24";
        }
        
        
        if(tml13 > localidadmayorcantmujeres){
            localidadmayorcantmujeres = tml13;
            Localidadmayorcantmujeres = "Localidad 1";
            pm = "Partido 3";
            pmcm = "Provincia 1 - 12";
        }else if(tml13_> localidadmayorcantmujeres){
            localidadmayorcantmujeres = tml13_;
            Localidadmayorcantmujeres = "Localidad 1";
            pm = "Partido 3";
            pmcm = "Provincia 12 - 24";
        }
        if(tml23 > localidadmayorcantmujeres){
            localidadmayorcantmujeres = tml23;
            Localidadmayorcantmujeres = "Localidad 2";
            pm = "Partido 3";
            pmcm = "Provincia 1 - 12";
        }else if(tml23_> localidadmayorcantmujeres){
            localidadmayorcantmujeres = tml23_;
            Localidadmayorcantmujeres = "Localidad 2";
            pm = "Partido 3";
            pmcm = "Provincia 12 - 24";
        }
        if(tml33 > localidadmayorcantmujeres){
            localidadmayorcantmujeres = tml33;
            Localidadmayorcantmujeres = "Localidad 3";
            pm = "Partido 3";
            pmcm = "Provincia 1 - 12";
        }else if(tml33_> localidadmayorcantmujeres){
            localidadmayorcantmujeres = tml33_;
            Localidadmayorcantmujeres = "Localidad 3";
            pm = "Partido 3";
            pmcm = "Provincia 12 - 24";
        }
    }

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        numpro = jComboBox1.getSelectedItem().toString();
        numpart = jComboBox2.getSelectedItem().toString();
        numlocal = jComboBox3.getSelectedItem().toString();
        chh = Integer.parseInt(jTextField3.getText());
        chm = Integer.parseInt(jTextField4.getText());

        proced_Literal_a();
        proced_literalA2();
        proced_literalA22();
        proced_literalA23();
        Literal_B();
        Literal_D();

        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        jComboBox3.setSelectedIndex(0);
        jTextField3.setText("");
        jTextField4.setText("");

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Partido: " + "1" + "\n"
                + "Cantidad Total de Habitantes: " + totalp1 + "\n"
                + "Localidad con mayor cantidad de habitantes: " + Mlp);
        JOptionPane.showMessageDialog(null, "Partido: " + "2" + "\n"
                + "Cantidad Total de Habitantes: " + totalp2 + "\n"
                + "Localidad con mayor cantidad de habitantes: " + Mlp2);
        JOptionPane.showMessageDialog(null, "Partido: " + "3" + "\n"
                + "Cantidad Total de Habitantes: " + totalp3 + "\n"
                + "Localidad con mayor cantidad de habitantes: " + Mlp3);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Numero de Provincia con mayor cantidad de Habitantes: "
                + Provinciamayorcantidad);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Literal_C();
        JOptionPane.showMessageDialog(null, "Numero de Provincia con menor cantidad de localidades censadas: "
                + Provinciamenorcantidad);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"LOCALIDAD CON MAYOR CANTIDAD DE HABITANTES MUJERES:" + "\n" + 
                "Localidad: " + Localidadmayorcantmujeres + "\n" + 
                "Partido: " + pm + "\n" + 
                "Provincia: " + pmcm);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm04_RegistroNacional.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm04_RegistroNacional.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm04_RegistroNacional.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm04_RegistroNacional.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm04_RegistroNacional().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
