/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulario_Integradores;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Charlie Cordova
 */
public class frm06_Subgrupos extends javax.swing.JFrame {

    /**
     * Creates new form frm06_Subgrupos
     */
    public frm06_Subgrupos() {
        initComponents();
        setSize(282, 200);
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Subgrupo de numeros");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Botones de accion para los subgrupos:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jButton1.setText("Mostrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 80, -1));

        jButton2.setText("Literal A");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 80, -1));

        jButton3.setText("Literal B");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 80, -1));

        jButton4.setText("Literal C");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 80, -1));

        jButton5.setText("Cancelar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    List<Integer> Subconjunto = new ArrayList<>(Arrays.asList(-13, 0, 25, 0, -31, 0, -41, 0, -53));
    List<Integer> Subconjunto2 = new ArrayList<>(Arrays.asList(18, 0, 23, 0, 32, 0, -46, 0, 59));
    List<Integer> Subconjunto3 = new ArrayList<>(Arrays.asList(-17, 0, -28, 0, 35, 0, 47, 0, -52));

    ///Literal A:
    public void informarSubgrupoConPrimoMasGrande() {
        int maxPrimo = -1;
        int subgrupoMaxPrimo = -1;
        for (int i = 0; i < 3; i++) {
            List<Integer> subgrupoActual = obtenerSubgrupo(i + 1);

            int primoMasGrande = encontrarPrimoMasGrande(subgrupoActual);

            if (primoMasGrande > maxPrimo) {
                maxPrimo = primoMasGrande;
                subgrupoMaxPrimo = i + 1;
            }
        }
        JOptionPane.showMessageDialog(null, "El subgrupo con el número primo más grande es el Subgrupo " + subgrupoMaxPrimo
                + " con el número primo: " + maxPrimo);
    }

    private List<Integer> obtenerSubgrupo(int numero) {
        switch (numero) {
            case 1:
                return Subconjunto;
            case 2:
                return Subconjunto2;
            case 3:
                return Subconjunto3;
            default:
                return new ArrayList<>();
        }
    }

    private int encontrarPrimoMasGrande(List<Integer> subgrupo) {
        int maxPrimo = -1;
        int subgrupoMaxPrimo = -1;
        for (int numero : subgrupo) {
            if (esPrimo(numero) && numero > maxPrimo) {
                maxPrimo = numero;
            }
        }
        return maxPrimo;
    }

    private boolean esPrimo(int numero) {
        if (numero <= 1) {
            return false;
        }

        for (int i = 2; i <= Math.sqrt(numero); i++) {
            if (numero % i == 0) {
                return false;
            }
        }
        return true;
    }

    ///Literal B:
    public void informarSubgrupoConMayorProporcionNegativos() {
        double maxProporcionNegativos = -1;
        int subgrupoMaxPropNegativos = -1;

        for (int i = 1; i <= 3; i++) {
            List<Integer> subgrupoActual = obtenerSubgrupo(i);

            double proporcionNegativos = calcularProporcionNegativos(subgrupoActual);

            if (proporcionNegativos > maxProporcionNegativos) {
                maxProporcionNegativos = proporcionNegativos;
                subgrupoMaxPropNegativos = i;
            }
        }

        JOptionPane.showMessageDialog(null, "El subgrupo con la mayor proporción de números negativos es el Subgrupo "
                + subgrupoMaxPropNegativos + " con una proporción de: " + maxProporcionNegativos);
    }

    private double calcularProporcionNegativos(List<Integer> subgrupo) {
        int totalNegativos = 0;
        int totalNumeros = subgrupo.size();

        for (int numero : subgrupo) {
            if (numero < 0) {
                totalNegativos++;
            }
        }

        if (totalNumeros == 0) {
            return 0; // Evitar división por cero si el subgrupo está vacío
        }

        return (double) totalNegativos / totalNumeros;
    }

    ///Literal C:
    
    public void informarMayorMultiploDe5() {
        for (int i = 1; i <= 3; i++) {
            List<Integer> subgrupoActual = obtenerSubgrupo(i);

            int mayorMultiploDe5 = encontrarMayorMultiploDe5(subgrupoActual);

            if (mayorMultiploDe5 != -1) {
                JOptionPane.showMessageDialog(null, "El mayor múltiplo de 5 en el Subgrupo " + i + " es: " + mayorMultiploDe5);
            } else {
                JOptionPane.showMessageDialog(null, "No hay múltiplos de 5 en el Subgrupo " + i);
            }
        }
    }

    private int encontrarMayorMultiploDe5(List<Integer> subgrupo) {
        int mayorMultiploDe5 = -1;

        for (int numero : subgrupo) {
            if (numero % 5 == 0 && numero > mayorMultiploDe5) {
                mayorMultiploDe5 = numero;
            }
        }

        return mayorMultiploDe5;
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "LISTA DE SUBGRUPOS:" + "\n"
                + "SUBGRUPOS :" + "\n"
                + "Subgrupo 1: " + Subconjunto + "\n"
                + "Subgrupo 2: " + Subconjunto2 + "\n"
                + "Subgrupo 3: " + Subconjunto3 + "\n");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        informarSubgrupoConPrimoMasGrande();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        informarSubgrupoConMayorProporcionNegativos();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        informarMayorMultiploDe5();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm06_Subgrupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm06_Subgrupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm06_Subgrupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm06_Subgrupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm06_Subgrupos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
