/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulario_Integradores;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Charlie Cordova
 */
public class frm09_Encomiendas extends javax.swing.JFrame {

    /**
     * Creates new form frm09_Encomiendas
     */
    public frm09_Encomiendas() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Registro de Encomiendas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Seleccione un Camion:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccione uno>", "Camion 1", "Camion 2", "Camion 3", "Camion 4", "Camion 5" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 220, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Agregue el peso de su encomienda:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 150, 30));

        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jButton2.setText("Literal A");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        jButton3.setText("Literal B");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, -1, -1));

        jButton4.setText("Salir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 70, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    List<Integer> Camion1 = new ArrayList<>();
    List<Integer> Camion2 = new ArrayList<>();
    List<Integer> Camion3 = new ArrayList<>();
    List<Integer> Camion4 = new ArrayList<>();
    List<Integer> Camion5 = new ArrayList<>();
    
    String Camion = "", nc1 = "", nc2 = "", nc3 = "", nc4 = "", nc5 = "", Ctmce = "";
    int peso_encomienda = 0, tc1 = 0, tc2 = 0, tc3 = 0, tc4 = 0, tc5 = 0, ctmce = 0,
        cont1 = 0,cont2 = 0,cont3 = 0,cont4 = 0,cont5 = 0;

    public void proced_numero_peso_total() {
        if (Camion.equals("Camion 1")) {
            cont1++;
            tc1 += peso_encomienda;
            Camion1.add(peso_encomienda);
            nc1 = Camion;
            if (tc1 >= 200) {
                Camion1.clear();
                cont1 = 0;
                tc1 = 0;
                nc1 = "";
                JOptionPane.showMessageDialog(null, "El peso de las encomiendas que " + "\n"
                        + "ha ingresado a excedido la capacidad del camion, " + "\n"
                        + "por lo tanto se reiniciara el peso.");
            }
        } else if (Camion.equals("Camion 2")) {
            cont2++;
            tc2 += peso_encomienda;
            Camion2.add(peso_encomienda);
            nc2 = Camion;
            if (tc2 >= 200) {
                cont2--;
                tc2 = 0;
                nc2 = "";
                JOptionPane.showMessageDialog(null, "El peso de las encomiendas que " + "\n"
                        + "ha ingresado a excedido la capacidad del camion, " + "\n"
                        + "por lo tanto se reiniciara el peso.");       
            }
        } else if (Camion.equals("Camion 3")) {
            cont3++;
            tc3 += peso_encomienda;
            Camion3.add(peso_encomienda);
            nc3 = Camion;
            if (tc3 >= 200) {
                cont3--;
                tc3 = 0;
                nc3 = "";
                JOptionPane.showMessageDialog(null, "El peso de las encomiendas que " + "\n"
                        + "ha ingresado a excedido la capacidad del camion, " + "\n"
                        + "por lo tanto se reiniciara el peso.");   
            }
        } else if (Camion.equals("Camion 4")) {
            cont4++;
            tc4 += peso_encomienda;
            Camion4.add(peso_encomienda);
            nc4 = Camion;
            if (tc4 >= 200) {
                cont4--;
                tc4 = 0;
                nc4 = "";
                JOptionPane.showMessageDialog(null, "El peso de las encomiendas que " + "\n"
                        + "ha ingresado a excedido la capacidad del camion, " + "\n"
                        + "por lo tanto se reiniciara el peso.");
            }
        } else if (Camion.equals("Camion 5")) {
            cont5++;
            tc5 += peso_encomienda;
            Camion5.add(peso_encomienda);
            nc5 = Camion;
            if (tc5 >= 200) {
                cont5--;
                tc5 = 0;
                nc5 = "";
                JOptionPane.showMessageDialog(null, "El peso de las encomiendas que " + "\n"
                        + "ha ingresado a excedido la capacidad del camion, " + "\n"
                        + "por lo tanto se reiniciara el peso.");
            }
        }
    }
    
    public void proced_mayorcant_encomiendas(){
        ctmce = 0;
        if(cont1 > ctmce){
            ctmce=cont1;
            Ctmce = "Camion 1";
        }
        if(cont2 > ctmce){
            ctmce=cont2;
            Ctmce = "Camion 2";
        }
        if(cont3 > ctmce){
            ctmce=cont3;
            Ctmce = "Camion 3";
        }
        if(cont4 > ctmce){
            ctmce=cont4;
            Ctmce = "Camion 4";
        }
        if(cont5 > ctmce){
            ctmce=cont5;
            Ctmce = "Camion 5";
        }
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Camion = jComboBox1.getSelectedItem().toString();
        peso_encomienda = Integer.parseInt(jTextField1.getText());

        proced_numero_peso_total();

        jComboBox1.setSelectedIndex(0);
        jTextField1.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "CAMION 1 :" + "\n"
                + "Numero del Camion: " + nc1 + "\n"
                + "Total de encomiendas: " + Camion1 + "\n");
        JOptionPane.showMessageDialog(null, "CAMION 2 :" + "\n"
                + "Numero del Camion: " + nc2 + "\n"
                + "Total de encomiendas: " + Camion2 + "\n");
        JOptionPane.showMessageDialog(null, "CAMION 3 :" + "\n"
                + "Numero del Camion: " + nc3 + "\n"
                + "Total de encomiendas: " + Camion3 + "\n");
        JOptionPane.showMessageDialog(null, "CAMION 4 :" + "\n"
                + "Numero del Camion: " + nc4 + "\n"
                + "Total de encomiendas: " + Camion4 + "\n");
        JOptionPane.showMessageDialog(null, "CAMION 5 :" + "\n"
                + "Numero del Camion: " + nc5 + "\n"
                + "Total de encomiendas: " + Camion5 + "\n");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        proced_mayorcant_encomiendas();
        JOptionPane.showMessageDialog(null,"El número de camión que transporta mayor cantidad de encomiendas es: " + Ctmce + "\n" +
                "con la cantidad de: " + ctmce);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm09_Encomiendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm09_Encomiendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm09_Encomiendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm09_Encomiendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm09_Encomiendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
