/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulario_Integradores;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Charlie Cordova
 */
public class frm07_EmpresaTextil extends javax.swing.JFrame {

    /**
     * Creates new form frm07_EmpresaTelas
     */
    public frm07_EmpresaTextil() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Empresa Textil");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jLabel2.setText("Numero de Pieza:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel3.setText("Nombre de la Pieza:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel4.setText("N. del Cliente que la Solicito:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel5.setText("C. de Piezas Vendidas:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 70, 30));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 100, 30));

        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 80, -1));

        jButton2.setText("Literal A");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 80, -1));

        jButton3.setText("Literal B");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccione uno>", "123", "456", "789" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 120, 30));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccione uno>", "Algodon(123)", "Lino(456)", "Nailon(789)" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 120, 30));

        jButton5.setText("Literal C");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        NumeroP = jComboBox1.getSelectedItem().toString();
        NombreP = jComboBox2.getSelectedItem().toString();
        ncs = Integer.parseInt(jTextField3.getText());
        cpv = Integer.parseInt(jTextField4.getText());

        proced_Ingreso_acumulacion();

        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        jTextField3.setText("");
        jTextField4.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "INFORMACION SOBRE EL PRODUCTO 123: " + "\n"
                + "Numero de la Pieza: " + "123" + "\n"
                + "Nombre de la Pieza: " + "Algodon" + "\n"
                + "Numero de clientes que la solicitaron: " + tncs + "\n"
                + "Cantidad de Piezas Vendidas: " + tcpv);
        JOptionPane.showMessageDialog(null, "INFORMACION SOBRE EL PRODUCTO 456: " + "\n"
                + "Numero de la Pieza: " + "456" + "\n"
                + "Nombre de la Pieza: " + "Lino" + "\n"
                + "Numero de clientes que la solicitaron: " + tncsl + "\n"
                + "Cantidad de Piezas Vendidas: " + tcpvl);
        JOptionPane.showMessageDialog(null, "INFORMACION SOBRE EL PRODUCTO 789: " + "\n"
                + "Numero de la Pieza: " + "789" + "\n"
                + "Nombre de la Pieza: " + "Nailon" + "\n"
                + "Numero de clientes que la solicitaron: " + tncsn + "\n"
                + "Cantidad de Piezas Vendidas: " + tcpvn);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        proced_informar_num_piezas();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        proced_numero_piezas_ms();
        JOptionPane.showMessageDialog(null,"El numero de pieza menos solicitado fue: " + Pms);
    }//GEN-LAST:event_jButton5ActionPerformed

    List<String> cantP10 = new ArrayList<>();
    
    int ncs = 0, cpv = 0, tncs = 0, tcpv = 0, tncsl = 0, tcpvl = 0, tncsn = 0, tcpvn = 0,pms = Integer.MAX_VALUE;
    String NombreP = "", NumeroP = "", Pms = "";

    public void proced_Ingreso_acumulacion(){
        if(NumeroP.equals("123")){
            if(NombreP.equals("Algodon(123)")){
                tncs += ncs;
                tcpv += cpv;
            }
        }else if(NumeroP.equals("456")){
            if(NombreP.equals("Lino(456)")){
                tncsl += ncs;
                tcpvl += cpv;
            }
        }else if(NumeroP.equals("789")){
            if(NombreP.equals("Nailon(789)")){
                tncsn += ncs;
                tcpvn += cpv;
            }
        }
    }
    
    public void proced_informar_num_piezas(){
        if(tncs > 10 || tncsl > 10 || tncsn > 10 ){
            if (tncs > 10) {
                cantP10.add("123");
            }
            if (tncsl > 10) {
                cantP10.add("456");
            }
            if (tncsn > 10) {
                cantP10.add("789");
            }
            JOptionPane.showMessageDialog(null, "Los numeros de piezas que fueron pedidos por mas de 10 clientes fueron: "
                    + cantP10);
        } else {
            JOptionPane.showMessageDialog(null, "Aun no se tiene registro de tal cantidad de pedidos");
        }
    }
    
    public void proced_numero_piezas_ms(){
        if(pms >= tcpv){
            pms = tcpv;
            Pms = "123";
        }
        if(pms >= tcpvl){
            pms = tcpvl;
            Pms = "456";
        }
        if(pms >= tcpvn){
            pms = tcpvn;
            Pms = "789";
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm07_EmpresaTextil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm07_EmpresaTextil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm07_EmpresaTextil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm07_EmpresaTextil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm07_EmpresaTextil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
