/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulario_Integradores;

import javax.swing.JOptionPane;

/**
 *
 * @author Charlie Cordova
 */
public class frm05_FabricaOperarios extends javax.swing.JFrame {

    /**
     * Creates new form frm05_FabricaOperarios
     */
    public frm05_FabricaOperarios() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(this);
        n = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese el numero de empleados: "));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Registro Fabrica de Pirotecnia");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setText("Turno:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccione uno>", "Diurno", "Nocturno" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 180, 30));

        jLabel3.setText("Numero de Legajo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel4.setText("Nombre del Empleado:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 130, 30));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 110, 30));

        jLabel5.setText("Horas Trabajadas en el dia:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 80, 30));

        jLabel6.setText("Codigo del dia:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccione uno>", "D (Domingo)", "X (Otro dia)" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 140, 30));

        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 80, -1));

        jButton2.setText("Media");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 80, -1));

        jButton3.setText("Informar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 80, -1));

        jButton4.setText("Salir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 80, -1));

        jLabel7.setText("...");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String Turno = "", nl = "", ne = "", codigodia = "", mayorne = "", mayornl = "";
    int horastrabajadas = 0, n = 0, i = 1, contD = 0, contN = 0;
    double sueldo = 0, sueldot = 0, totalnocturno = 0, promedio_n = 0, mayorsueldot = 0;

    public void habilitar(boolean bol) {
        jTextField1.setEditable(bol);
        jTextField2.setEditable(bol);
        jTextField3.setEditable(bol);
        jComboBox1.setEnabled(bol);
        jComboBox2.setEnabled(bol);
    }

    public void proced_pago_abono_adicional() {
        if (codigodia.equals("D (Domingo)")) {
            if (Turno.equals("Diurno")) {
                contD++;
                sueldo = horastrabajadas * 4;
                sueldot = sueldo * 1.50;
            } else if (Turno.equals("Nocturno")) {
                contN++;
                sueldo = horastrabajadas * 5;
                sueldot = sueldo * 1.50;
                totalnocturno += horastrabajadas;

            }
        }
        else if (codigodia.equals("X (Otro dia)")) {
            if (Turno.equals("Diurno")) {
                contD++;
                sueldo = horastrabajadas * 4;
                sueldot = sueldo;
            } else if (Turno.equals("Nocturno")) {
                contN++;
                sueldo = horastrabajadas * 5;
                sueldot = sueldo;
                totalnocturno += horastrabajadas;
            }
        }
    }
    
    public double proced_promedio_operarios_nocturnos(){
        if(Turno.equals("Nocturno")){
            promedio_n = totalnocturno/contN;
        }
        return promedio_n;
    }
    
    public void proced_informarmax_nu_ope(){
        if(sueldot > mayorsueldot){
            mayorsueldot = sueldot;
            mayorne = ne;
            mayornl = nl;
        }
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (n >= 0) {
            Turno = jComboBox1.getSelectedItem().toString();
            nl = jTextField1.getText();
            ne = jTextField2.getText();
            horastrabajadas = Integer.parseInt(jTextField3.getText());
            codigodia = jComboBox2.getSelectedItem().toString();

            jComboBox1.setSelectedIndex(0);
            jComboBox2.setSelectedIndex(0);
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");

            jLabel7.setText(i + "/" + n);
            if (i == n) {
                habilitar(false);
            }
            i = i + 1;
        }
        proced_pago_abono_adicional();
        proced_promedio_operarios_nocturnos();
        proced_informarmax_nu_ope();
        JOptionPane.showMessageDialog(null, "Nombre del Empleado: " + ne + "\n"
                + "Numero de Legajo: " + nl + "\n"
                + "Turno: " + Turno + "\n"
                + "Sueldo: " + sueldot + "\n");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Promedio de horas trabajadas por los operarios nocturnos: " + promedio_n);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"OPERARIO QUE COBRA EL MAXIMO JORNAL:" + "\n" + 
                "Nombre del Operario: " + mayorne + "\n" + 
                "Numero de Legajo:" + mayornl + "\n" + 
                "Sueldo:" + mayorsueldot);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm05_FabricaOperarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm05_FabricaOperarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm05_FabricaOperarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm05_FabricaOperarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm05_FabricaOperarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
