/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import javax.swing.JOptionPane;

/**
 *
 * @author Charlie Cordova
 */
public class frm05_Peso extends javax.swing.JFrame {

    /**
     * Creates new form frm05_Peso
     */
    public frm05_Peso() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Programa para Calcular el Peso");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Por favor, ingrese los siguientes datos:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Estatura:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Peso:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Edad:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Paciente:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 260, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 260, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 260, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 260, -1));

        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\Imagenes para Netbeans 8.2\\Medicina.jpg")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 200, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String Paciente = "";
    double estatura = 0, peso = 0, pesot = 0;
    int edad = 0;

    public void Calcular_Peso() {
        pesot = (estatura - peso) / 100;
        if (edad <= 20) {
            if (pesot >= 0.90 && pesot <= 1.10) {
                JOptionPane.showMessageDialog(null, "El paciente " + Paciente + "\n"
                        + "Con un peso de: " + peso + " kg" + "\n"
                        + "Con una estatura de: " + estatura + "\n"
                        + "Tiene un Peso Normal: " + pesot + " kg");
            } else if (pesot > 1.10) {
                JOptionPane.showMessageDialog(null, "El paciente " + Paciente + "\n"
                        + "Con un peso de: " + peso + " kg" + "\n"
                        + "Con una estatura de: " + estatura + "\n"
                        + "Tiene Bajo Peso: " + pesot + " kg");
            } else if (pesot < 0.90) {
                JOptionPane.showMessageDialog(null, "El paciente " + Paciente + "\n"
                        + "Con un peso de: " + peso + " kg" + "\n"
                        + "Con una estatura de: " + estatura + "\n"
                        + "Esta excedido de Peso: " + pesot + " kg");
            }
        }
        if (edad > 20 && edad <= 30) {
            if (pesot >= 0.85 && pesot <= 1.15) {
                JOptionPane.showMessageDialog(null, "El paciente " + Paciente + "\n"
                        + "Con un peso de: " + peso + " kg" + "\n"
                        + "Con una estatura de: " + estatura + "\n"
                        + "Tiene un Peso Normal: " + pesot + " kg");
            } else if (pesot > 1.15) {
                JOptionPane.showMessageDialog(null, "El paciente " + Paciente + "\n"
                        + "Con un peso de: " + peso + " kg" + "\n"
                        + "Con una estatura de: " + estatura + "\n"
                        + "Tiene Bajo Peso: " + pesot + " kg");
            } else if (pesot < 0.85) {
                JOptionPane.showMessageDialog(null, "El paciente " + Paciente + "\n"
                        + "Con un peso de: " + peso + " kg" + "\n"
                        + "Con una estatura de: " + estatura + "\n"
                        + "Esta excedido de Peso: " + pesot + " kg");
            }
        }
        if (edad > 30 && edad <= 40) {
            if (pesot >= 0.80 && pesot <= 1.10) {
                JOptionPane.showMessageDialog(null, "El paciente " + Paciente + "\n"
                        + "Con un peso de: " + peso + " kg" + "\n"
                        + "Con una estatura de: " + estatura + "\n"
                        + "Tiene un Peso Normal: " + pesot + " kg");
            } else if (pesot > 1.10) {
                JOptionPane.showMessageDialog(null, "El paciente " + Paciente + "\n"
                        + "Con un peso de: " + peso + " kg" + "\n"
                        + "Con una estatura de: " + estatura + "\n"
                        + "Tiene Bajo Peso: " + pesot + " kg");
            } else if (pesot < 0.80) {
                JOptionPane.showMessageDialog(null, "El paciente " + Paciente + "\n"
                        + "Con un peso de: " + peso + " kg" + "\n"
                        + "Con una estatura de: " + estatura + "\n"
                        + "Esta excedido de Peso: " + pesot + " kg");
            }
        }
        if (edad > 40) {
            if (pesot >= 0.75 && pesot <= 1.10) {
                JOptionPane.showMessageDialog(null, "El paciente " + Paciente + "\n"
                        + "Con un peso de: " + peso + " kg" + "\n"
                        + "Con una estatura de: " + estatura + "\n"
                        + "Tiene un Peso Normal: " + pesot + " kg");
            } else if (pesot > 1.10) {
                JOptionPane.showMessageDialog(null, "El paciente " + Paciente + "\n"
                        + "Con un peso de: " + peso + " kg" + "\n"
                        + "Con una estatura de: " + estatura + "\n"
                        + "Tiene Bajo Peso: " + pesot + " kg");
            } else if (pesot < 0.75) {
                JOptionPane.showMessageDialog(null, "El paciente " + Paciente + "\n"
                        + "Con un peso de: " + peso + " kg" + "\n"
                        + "Con una estatura de: " + estatura + "\n"
                        + "Esta excedido de Peso: " + pesot + " kg");
            }
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Paciente = jTextField1.getText();
        estatura = Double.parseDouble(jTextField2.getText());
        peso = Double.parseDouble(jTextField3.getText());
        edad = Integer.parseInt(jTextField4.getText());

        Calcular_Peso();

        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm05_Peso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm05_Peso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm05_Peso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm05_Peso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm05_Peso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
