package Formularios;

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Charlie Cordova
 */
public class frm08_CompañiaElectrica extends javax.swing.JFrame {

    /**
     * Creates new form frm08_CompañiaElectrica
     */
    public frm08_CompañiaElectrica() {
        initComponents();
        setLocationRelativeTo(this);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Corporacion Nacional de Electricidad");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel2.setText("Zona:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel3.setText("N. del Cliente:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        jLabel4.setText("L. del medidor del mes actual:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel5.setText("L. del medidor del mes anterior:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccione uno>", "Zona 1", "Zona 2", "Zona 3", "Zona 4", "Zona 5", "Zona 6", "Zona 7", "Zona 8", "Zona 9", "Zona 10" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 80, 30));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 80, 30));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 140, 30));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 140, 30));

        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String Zona = "";
    int nc = 0, contZ1 = 0, contZ2 = 0, contZ3 = 0, contZ4 = 0, contZ5 = 0,
            contZ6 = 0, contZ7 = 0, contZ8 = 0, contZ9 = 0, contZ10 = 0;
    double lact = 0, lant = 0, consumot = 0, importe = 0;
    double costoz1 = 0, costoz2 = 0, costoz3 = 0, costoz4 = 0, costoz5 = 0,
            costoz6 = 0, costoz7 = 0, costoz8 = 0, costoz9 = 0, costoz10 = 0;

    public void proced_consumo_energetico() {
        if (Zona.equals("Zona 1")) {
            contZ1++;
            consumot = lact + lant;
            if (consumot <= 100) {
                importe = 0.10 * consumot;
                costoz1 += importe;
            } else if (consumot >= 101 && consumot <= 200) {
                importe = (0.10 * 100) + (consumot - 100) * 0.12;
                costoz1 += importe;
            } else if (consumot >= 201) {
                importe = (0.10 * 100) + (0.12 * 100) + (consumot - 200) * 0.15;
                costoz1 += importe;
            }
            JOptionPane.showMessageDialog(null, "Zona: " + Zona + "\n"
                    + "Cantidad de Uusarios en la Zona: " + contZ1 + "\n"
                    + "Total Facturado en la Zona: " + costoz1);

        } else if (Zona.equals("Zona 2")) {
            contZ2++;
            consumot = lact + lant;
            if (consumot <= 100) {
                importe = 0.10 * consumot;
                costoz2 += importe;
            } else if (consumot >= 101 && consumot <= 200) {
                importe = (0.10 * 100) + (consumot - 100) * 0.12;
                costoz2 += importe;
            } else if (consumot >= 201) {
                importe = (0.10 * 100) + (0.12 * 100) + (consumot - 200) * 0.15;
                costoz2 += importe;
            }
            JOptionPane.showMessageDialog(null, "Zona: " + Zona + "\n"
                    + "Cantidad de Uusarios en la Zona: " + contZ2 + "\n"
                    + "Total Facturado en la Zona: " + costoz2);

        } else if (Zona.equals("Zona 3")) {
            contZ3++;
            consumot = lact + lant;
            if (consumot <= 100) {
                importe = 0.10 * consumot;
                costoz3 += importe;
            } else if (consumot >= 101 && consumot <= 200) {
                importe = (0.10 * 100) + (consumot - 100) * 0.12;
                costoz3 += importe;
            } else if (consumot >= 201) {
                importe = (0.10 * 100) + (0.12 * 100) + (consumot - 200) * 0.15;
                costoz3 += importe;
            }
            JOptionPane.showMessageDialog(null, "Zona: " + Zona + "\n"
                    + "Cantidad de Uusarios en la Zona: " + contZ3 + "\n"
                    + "Total Facturado en la Zona: " + costoz3);
        } else if (Zona.equals("Zona 4")) {
            contZ4++;
            consumot = lact + lant;
            if (consumot <= 100) {
                importe = 0.10 * consumot;
                costoz4 += importe;
            } else if (consumot >= 101 && consumot <= 200) {
                importe = (0.10 * 100) + (consumot - 100) * 0.12;
                costoz4 += importe;
            } else if (consumot >= 201) {
                importe = (0.10 * 100) + (0.12 * 100) + (consumot - 200) * 0.15;
                costoz4 += importe;
            }
            JOptionPane.showMessageDialog(null, "Zona: " + Zona + "\n"
                    + "Cantidad de Uusarios en la Zona: " + contZ4 + "\n"
                    + "Total Facturado en la Zona: " + costoz4);
        } else if (Zona.equals("Zona 5")) {
            contZ5++;
            consumot = lact + lant;
            if (consumot <= 100) {
                importe = 0.10 * consumot;
                costoz5 += importe;
            } else if (consumot >= 101 && consumot <= 200) {
                importe = (0.10 * 100) + (consumot - 100) * 0.12;
                costoz5 += importe;
            } else if (consumot >= 201) {
                importe = (0.10 * 100) + (0.12 * 100) + (consumot - 200) * 0.15;
                costoz5 += importe;
            }
            JOptionPane.showMessageDialog(null, "Zona: " + Zona + "\n"
                    + "Cantidad de Uusarios en la Zona: " + contZ5 + "\n"
                    + "Total Facturado en la Zona: " + costoz5);
        } else if (Zona.equals("Zona 6")) {
            contZ6++;
            consumot = lact + lant;
            if (consumot <= 100) {
                importe = 0.10 * consumot;
                costoz6 += importe;
            } else if (consumot >= 101 && consumot <= 200) {
                importe = (0.10 * 100) + (consumot - 100) * 0.12;
                costoz6 += importe;
            } else if (consumot >= 201) {
                importe = (0.10 * 100) + (0.12 * 100) + (consumot - 200) * 0.15;
                costoz6 += importe;
            }
            JOptionPane.showMessageDialog(null, "Zona: " + Zona + "\n"
                    + "Cantidad de Uusarios en la Zona: " + contZ6 + "\n"
                    + "Total Facturado en la Zona: " + costoz6);
        } else if (Zona.equals("Zona 7")) {
            contZ7++;
            consumot = lact + lant;
            if (consumot <= 100) {
                importe = 0.10 * consumot;
                costoz7 += importe;
            } else if (consumot >= 101 && consumot <= 200) {
                importe = (0.10 * 100) + (consumot - 100) * 0.12;
                costoz7 += importe;
            } else if (consumot >= 201) {
                importe = (0.10 * 100) + (0.12 * 100) + (consumot - 200) * 0.15;
                costoz7 += importe;
            }
            JOptionPane.showMessageDialog(null, "Zona: " + Zona + "\n"
                    + "Cantidad de Uusarios en la Zona: " + contZ7 + "\n"
                    + "Total Facturado en la Zona: " + costoz7);
        } else if (Zona.equals("Zona 8")) {
            contZ8++;
            consumot = lact + lant;
            if (consumot <= 100) {
                importe = 0.10 * consumot;
                costoz8 += importe;
            } else if (consumot >= 101 && consumot <= 200) {
                importe = (0.10 * 100) + (consumot - 100) * 0.12;
                costoz8 += importe;
            } else if (consumot >= 201) {
                importe = (0.10 * 100) + (0.12 * 100) + (consumot - 200) * 0.15;
                costoz8 += importe;
            }
            JOptionPane.showMessageDialog(null, "Zona: " + Zona + "\n"
                    + "Cantidad de Uusarios en la Zona: " + contZ8 + "\n"
                    + "Total Facturado en la Zona: " + costoz8);
        } else if (Zona.equals("Zona 9")) {
            contZ9++;
            consumot = lact + lant;
            if (consumot <= 100) {
                importe = 0.10 * consumot;
                costoz9 += importe;
            } else if (consumot >= 101 && consumot <= 200) {
                importe = (0.10 * 100) + (consumot - 100) * 0.12;
                costoz9 += importe;
            } else if (consumot >= 201) {
                importe = (0.10 * 100) + (0.12 * 100) + (consumot - 200) * 0.15;
                costoz9 += importe;
            }
            JOptionPane.showMessageDialog(null, "Zona: " + Zona + "\n"
                    + "Cantidad de Uusarios en la Zona: " + contZ9 + "\n"
                    + "Total Facturado en la Zona: " + costoz9);
        } else if (Zona.equals("Zona 10")) {
            contZ10++;
            consumot = lact + lant;
            if (consumot <= 100) {
                importe = 0.10 * consumot;
                costoz10 += importe;
            } else if (consumot >= 101 && consumot <= 200) {
                importe = (0.10 * 100) + (consumot - 100) * 0.12;
                costoz10 += importe;
            } else if (consumot >= 201) {
                importe = (0.10 * 100) + (0.12 * 100) + (consumot - 200) * 0.15;
                costoz10 += importe;
            }
            JOptionPane.showMessageDialog(null, "Zona: " + Zona + "\n"
                    + "Cantidad de Uusarios en la Zona: " + contZ10 + "\n"
                    + "Total Facturado en la Zona: " + costoz10);
        }
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Zona = jComboBox1.getSelectedItem().toString();
        nc = Integer.parseInt(jTextField1.getText());
        lact = Double.parseDouble(jTextField2.getText());
        lant = Double.parseDouble(jTextField3.getText());

        proced_consumo_energetico();

        jComboBox1.setSelectedIndex(0);
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm08_CompañiaElectrica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm08_CompañiaElectrica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm08_CompañiaElectrica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm08_CompañiaElectrica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm08_CompañiaElectrica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
