/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import javax.swing.JOptionPane;

/**
 *
 * @author Charlie Cordova
 */
public class frm10_Banco_Ahorros extends javax.swing.JFrame {

    /**
     * Creates new form frm10_Banco_Ahorros
     */
    public frm10_Banco_Ahorros() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Banco de Machala");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        jLabel2.setText("Codigo de la Sucursal:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccione uno>", "Codigo 1 - 10", "Codigo 11 - 20" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 220, 30));

        jLabel3.setText("N. Caja de Ahorros:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel4.setText("Tipo de Movimiento:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel5.setText("Importe del Movimiento:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 220, 30));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("E");
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("D");
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccione uno>", "123456", "654321", "678910", "109876" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 220, 30));

        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 50, 80, -1));

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 80, -1));

        jButton3.setText("Imprimir S.6 - 10");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 120, -1));

        jButton4.setText("Imprimir S.1 -5");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 120, -1));

        jButton5.setText("Imprimir Total. S");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 120, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String cs = "", nc = "";
    char movimiento = ' ';
    double importe = 0, TotalE = 0, TotalD = 0, TotalE2 = 0, TotalD2 = 0;
    int TcontE1 = 0, TcontE2 = 0, TcontD1 = 0, TcontD2 = 0;
    int contE = 0, contD = 0, contE2 = 0, contD2 = 0,
        contE3 = 0, contD3 = 0, contE4 = 0, contD4 = 0;
    int contE12 = 0, contD12 = 0, contE22 = 0, contD22 = 0,
        contE32 = 0, contD32 = 0, contE42 = 0, contD42 = 0;
    double Textracciones = 0, Tdepositos = 0,
            Textracciones2 = 0, Tdepositos2 = 0,
            Textracciones3 = 0, Tdepositos3 = 0,
            Textracciones4 = 0, Tdepositos4 = 0;
    double Textracciones12 = 0, Tdepositos12 = 0,
            Textracciones22 = 0, Tdepositos22 = 0,
            Textracciones32 = 0, Tdepositos32 = 0,
            Textracciones42 = 0, Tdepositos42 = 0;

    public void proced_total() {
        if (cs.equals("Codigo 1 - 10")) {
            if (nc.equals("123456")) {
                if (movimiento == 'E') {
                    contE++;
                    Textracciones += importe;
                    TotalE += importe;
                } else if (movimiento == 'D') {
                    contD++;
                    Tdepositos += importe;
                    TotalD += importe;
                }
            } else if (nc.equals("654321")) {
                if (movimiento == 'E') {
                    contE2++;
                    Textracciones2 += importe;
                    TotalE += importe;
                } else if (movimiento == 'D') {
                    contD2++;
                    Tdepositos2 += importe;
                    TotalD += importe;
                }
            } else if (nc.equals("678910")) {
                if (movimiento == 'E') {
                    contE3++;
                    Textracciones3 += importe;
                    TotalE += importe;
                } else if (movimiento == 'D') {
                    contD3++;
                    Tdepositos3 += importe;
                    TotalD += importe;
                }
            } else if (nc.equals("109876")) {
                if (movimiento == 'E') {
                    contE4++;
                    Textracciones4 += importe;
                    TotalE += importe;
                } else if (movimiento == 'D') {
                    contD4++;
                    Tdepositos4 += importe;
                    TotalD += importe;
                }
            }
        }
    }

    public void proced_total2() {
        if (cs.equals("Codigo 11 - 20")) {
            if (nc.equals("123456")) {
                if (movimiento == 'E') {
                    contE12++;
                    Textracciones12 += importe;
                    TotalE2 += importe;
                } else if (movimiento == 'D') {
                    contD12++;
                    Tdepositos12 += importe;
                    TotalD2 += importe;
                }
            } else if (nc.equals("654321")) {
                if (movimiento == 'E') {
                    contE22++;
                    Textracciones22 += importe;
                    TotalE2 += importe;
                } else if (movimiento == 'D') {
                    contD22++;
                    Tdepositos22 += importe;
                    TotalD2 += importe;
                }
            } else if (nc.equals("678910")) {
                if (movimiento == 'E') {
                    contE32++;
                    Textracciones32 += importe;
                    TotalE2 += importe;
                } else if (movimiento == 'D') {
                    contD32++;
                    Tdepositos32 += importe;
                    TotalD2 += importe;
                }
            } else if (nc.equals("109876")) {
                if (movimiento == 'E') {
                    contE42++;
                    Textracciones42 += importe;
                    TotalE2 += importe;
                } else if (movimiento == 'D') {
                    contD42++;
                    Tdepositos42 += importe;
                    TotalD2 += importe;
                }
            }
        }
    }
    
    public void proced_cant_cont(){
        TcontE1 = contE + contE2 + contE3 + contE4 ;
        TcontE2 = contE12 + contE22 + contE32 + contE42;
        TcontD1 = contD + contD2 + contD3 + contD4;
        TcontD2 = contD12 + contD22 + contD32 + contD42;
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cs = jComboBox1.getSelectedItem().toString();
        nc = jComboBox2.getSelectedItem().toString();
        if (jRadioButton1.isSelected()) {
            movimiento = 'E';
        } else if (jRadioButton2.isSelected()) {
            movimiento = 'D';
        }
        importe = Double.parseDouble(jTextField2.getText());

        proced_total();
        proced_total2();
        proced_cant_cont();

        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        buttonGroup1.clearSelection();
        jTextField2.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Sucursal: " + "1-10" + "\n"
                + "Caja de Ahorro:" + "123456" + "\n"
                + "Total de Extracciones: " + contE + " ------ " + " Importe total de Extracciones: " + Textracciones + " $" + "\n"
                + "Total de Depositos: " + contD + " ------ " + " Importe total de Depositos: " + Tdepositos + " $");
        JOptionPane.showMessageDialog(null,
                "Caja de Ahorro:" + "654321" + "\n"
                + "Total de Extracciones: " + contE2 + " ------ " + " Importe total de Extracciones: " + Textracciones2 + " $" + "\n"
                + "Total de Depositos: " + contD2 + " ------ " + " Importe total de Depositos: " + Tdepositos2 + " $");
        JOptionPane.showMessageDialog(null,
                "Caja de Ahorro:" + "678910" + "\n"
                + "Total de Extracciones: " + contE3 + " ------ " + " Importe total de Extracciones: " + Textracciones3 + " $" + "\n"
                + "Total de Depositos: " + contD3 + " ------ " + " Importe total de Depositos: " + Tdepositos3 + " $");
        JOptionPane.showMessageDialog(null,
                "Caja de Ahorro:" + "109876" + "\n"
                + "Total de Extracciones: " + contE4 + " ------ " + " Importe total de Extracciones: " + Textracciones4 + " $" + "\n"
                + "Total de Depositos: " + contD4 + " ------ " + " Importe total de Depositos: " + Tdepositos4 + " $");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Sucursal: " + "11-20" + "\n"
                + "Caja de Ahorro:" + "123456" + "\n"
                + "Total de Extracciones: " + contE12 + " ------ " + " Importe total de Extracciones: " + Textracciones12 + " $" + "\n"
                + "Total de Depositos: " + contD12 + " ------ " + " Importe total de Depositos: " + Tdepositos12 + " $");
        JOptionPane.showMessageDialog(null,
                "Caja de Ahorro:" + "654321" + "\n"
                + "Total de Extracciones: " + contE22 + " ------ " + " Importe total de Extracciones: " + Textracciones22 + " $" + "\n"
                + "Total de Depositos: " + contD22 + " ------ " + " Importe total de Depositos: " + Tdepositos22 + " $");
        JOptionPane.showMessageDialog(null,
                "Caja de Ahorro:" + "678910" + "\n"
                + "Total de Extracciones: " + contE32 + " ------ " + " Importe total de Extracciones: " + Textracciones32 + " $" + "\n"
                + "Total de Depositos: " + contD32 + " ------ " + " Importe total de Depositos: " + Tdepositos32 + " $");
        JOptionPane.showMessageDialog(null,
                "Caja de Ahorro:" + "109876" + "\n"
                + "Total de Extracciones: " + contE42 + " ------ " + " Importe total de Extracciones: " + Textracciones42 + " $" + "\n"
                + "Total de Depositos: " + contD42 + " ------ " + " Importe total de Depositos: " + Tdepositos42 + " $");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null, "Total de la Sucursal: " + "1-10" + "\n"
                + "Total de Extracciones: " + TcontE1 + " ------ " + " Importe total de Extracciones: " + TotalE + " $" + "\n"
                + "Total de Depositos: " + TcontD1 + " ------ " + " Importe total de Depositos: " + TotalD + " $");
        JOptionPane.showMessageDialog(null, "Total de la Sucursal: " + "11-20" + "\n"
                + "Total de Extracciones: " + TcontE2 + " ------ " + " Importe total de Extracciones: " + TotalE2 + " $" + "\n"
                + "Total de Depositos: " + TcontD2 + " ------ " + " Importe total de Depositos: " + TotalD2 + " $");
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm10_Banco_Ahorros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm10_Banco_Ahorros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm10_Banco_Ahorros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm10_Banco_Ahorros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm10_Banco_Ahorros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
